// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: "../public/font/MonaSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/MonaSans-Regular.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-myfont",
});

export default function RootLayout({ children }: any) {
  return (
    <html className={myFont.variable}>
      <body className="font-myfont">{children}</body>
    </html>
  );
}
